# Generated by Django 4.1.5 on 2023-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option0", models.TextField()),
                ("option1", models.TextField()),
                ("option2", models.TextField()),
                ("option3", models.TextField()),
            ],
        ),
    ]
