# Generated by Django 4.1.5 on 2023-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0002_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
